### PR TITLE
Fixes related to MAC Sequential model and COG dataset

### PR DESCRIPTION
**Pull request by tkornuta-ibm**

### CODE REVIEW

**Review by vincentalbouy — APPROVED** [review]

**Comment by tkornuta-ibm** [comment]
This pull request **introduces 1 alert** and **fixes 2** when merging ecb6e36e2eaa9cd0067f466f994fa97cf90d1b1e into f7e486e0ad3a00655307a17776263e7c382a0fdc - [view on LGTM.com](https://lgtm.com/projects/g/IBM/mi-prometheus/rev/pr-b6d21f77c417103c144d14c4759da487e8787e75)

**new alerts:**

* 1 for Unreachable code

**fixed alerts:**

* 2 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tkornuta-ibm** [comment]
This pull request **introduces 1 alert** and **fixes 3** when merging 8fe136def481a79c856febd17cbc149f57fd10fc into f7e486e0ad3a00655307a17776263e7c382a0fdc - [view on LGTM.com](https://lgtm.com/projects/g/IBM/mi-prometheus/rev/pr-661a4fe77767ac4beb508db16ea74f7c88ac9427)

**new alerts:**

* 1 for Unreachable code

**fixed alerts:**

* 3 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tkornuta-ibm** [comment]
This pull request **introduces 1 alert** and **fixes 3** when merging 40aaa2ef0281c227f5227b9a8d50545ec2dc4248 into f7e486e0ad3a00655307a17776263e7c382a0fdc - [view on LGTM.com](https://lgtm.com/projects/g/IBM/mi-prometheus/rev/pr-a3d8f657e4e89d9fc123bc927bc5c0f0b07bb44f)

**new alerts:**

* 1 for Unreachable code

**fixed alerts:**

* 3 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tkornuta-ibm** [comment]
This pull request **introduces 1 alert** and **fixes 3** when merging c0e7e12db1ef173a187321caee46f29b3c09d22e into f7e486e0ad3a00655307a17776263e7c382a0fdc - [view on LGTM.com](https://lgtm.com/projects/g/IBM/mi-prometheus/rev/pr-61d7639179e2ddf89ebd14187fb89f49aa8404e8)

**new alerts:**

* 1 for Unreachable code

**fixed alerts:**

* 3 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
